port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  allow_setting_keys: false
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  max_ttl_seconds: 3600
backend:
  type: "redis"
  redis:
    host: "redis-host-primary-endpoint-address"
    port: 6379
    db: 1
    expiration: 10 # in Minutes
    tls:
      enabled: false
      insecure_skip_verify: false
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none"
routes:
  allow_public_write: true
